### PR TITLE
Add tvos platform to podspec

### PR DESCRIPTION
**Pull request by nuudles**
Adds support for tvOS to the podspec

### CODE REVIEW

**Comment by Anviking** [comment]
:sparkles:

**Comment by ohwutup** [comment]
Did this update change the version number of the repo? If so, it can be pushed to CocoaPods, otherwise, we should submit a PR to https://github.com/CocoaPods/Specs to change https://github.com/CocoaPods/Specs/blob/master/Specs/Decodable/0.3.2/Decodable.podspec.json

**Comment by nuudles** [comment]
I didn't update the version number as I figured it should be up to the pod maintainer to do that.

**Comment by Anviking** [comment]
@ohwutup I don't know the extent of your interest of maintaining the podspec, but do you want to be added as a collaborator?

**Comment by Anviking** [comment]
Does that really work? https://github.com/CocoaPods/Specs/pull/12199

**Comment by ohwutup** [comment]
@Anviking id love to!

**Comment by ohwutup** [comment]
I made this a bit ago https://github.com/CocoaPods/Specs/pull/13514. Hopefully they will take a look soon, otherwise I can go in and bump the version and push a new one.

We should probably add OS X support too

**Comment by Anviking** [comment]
Awesome! :smile:

**Pull request merged**
