### PR TITLE
Add overload for => returning [String: AnyObject]?

### PR DESCRIPTION
**Pull request by jordanekay**

### CODE REVIEW

**Comment by Anviking** [comment]
Is this this for having `[String: AnyObject]` as the final return type? Would extending `Dictionary` to be `Decodable` work as well?

**Comment by jordanekay** [comment]
It's the same motivation as adding => [T]?. There's already a => [String: AnyObject] overload, for keys whose values are dictionaries. This just adds support for keys of that kind that also happen to be optional in your JSON schema (as is the case with => [T]?).

**Comment by Anviking** [comment]
Hmm, this leads to ambiguity. Right now the `a => [String: AnyObject]` overload exists (instead of making dictionary decodable) so that chaining `=>` works. (so that `j=>"key"` implicitly returns `[String: AnyObject]`). Thinking of changing the way nested keys (#8) work, but closing this for now.

**Comment by jordanekay** [comment]
Can my JSON schema not (optionally) include a key whose value is a dictionary, where that dictionary does not map directly to a Swift model object?

**Comment by Anviking** [comment]
If it's just a (sometimes) missing key somewhere in the "key path" things should just work because of the optional, non-throwing `=>`

**Pull request closed without merging**
