### PR TITLE
Make value public to be able to extract the decoded objects

### PR DESCRIPTION
**Pull request by JaviSoto**

### CODE REVIEW

**Comment by Anviking** [comment]
Any specific reason? If this is for decoding into arrays (like `j => "array"`), [these] (https://github.com/Anviking/Decodable/blob/master/Decodable/PlsFixSwift.swift#L55L93) overloads should make it work.

**Comment by JaviSoto** [comment]
I guess I'm probably missing something. Which method should I be using to decode a `j: AnyObject` that's an array like:

```JSON
[
 { "Key":"value",
 "key2":"value"},
 { "Key":"value",
 "key2":"value"}
]
```
This is, there's no key with a string value to access the array of dictionaries.

**Comment by Anviking** [comment]
Oh, now I see. You're right, there is no way. Merging this. Thanks @JaviSoto!

**Comment by JaviSoto** [comment]
Awesome thanks!

**Pull request merged**
